apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: productpage:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: GROUP_NUM
          value: "29"  
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
spec:
  selector:
    app: productpage
  ports:
    - protocol: TCP
      port: 80  # Puerto expuesto del servicio
      targetPort: 9080  # Puerto interno del contenedor
  type: LoadBalancer  # Para acceder desde fuera del clúster
